[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

build_flags =
    -std=gnu++17
    -I../../common          ; shared Protocol.h (common/ at repo root)
    -Wall
    -Wextra

monitor_speed  = 115200
upload_speed   = 921600
